"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { ToastContainer } from "react-toastify";
// import "react-toastify/dist/ReactToastify.css";
import { redirect, usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import Cookies from "universal-cookie";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isAccess, setIsAccess] = useState<boolean>(false);
  const pathName = usePathname();
  const cookies = new Cookies();
  const router = useRouter();
  // const token = localStorage.getItem("token")
  const token = cookies.get("token");

  // useEffect(() => {
  //   if (pathName === "/") {
  //     if (token) {
  //       setIsAccess(true);
  //     } else {
  //       setIsAccess(false);
  //       cookies.remove("token");
  //       cookies.remove("userId");
  //       router.push("/signin");
  //     }
  //   } else {
  //     setIsAccess(true);
  //   }
  // }, [pathName]);

  if (!token && pathName !== "/signin" && pathName !== "/signup") {
    redirect("/signin");
  }

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      {/* <ToastContainer /> */}
    </html>
  );
}
